server:
  port: 8082
ops: window
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/collreach_userlogin
    username: root
    password: Sensitive@1
  security:
    user:
      name: ayush
      password: pass
      roles: manager
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true